spring:
  application:
    name: modulo2.2

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/anajulia?serverSelectionTimeoutMs=15000&connectTimeoutMS=15000

server:
  port: 8081

secret:
  key: "o36pEukmNV48mJkKkRt8GoYtfbXfszupz6Zrq6jPAEC"